name: SubstitueUser
version: "0.1"
api-version: "1.13"
description: "SubstitueUser"

author: Teddy
authors: []
website: https://twieteddy.github.io

main: io.github.twieteddy.substituteuser.SubstitueUser
database: false
depend: []
softdepend: []

permissions:
  substituteuser.su:
    default: op
  substitueuser.su.skippermissioncheck:
    default: false

commands:
  su:
    description: Execute something as somebody else
    permission: substituteuser.su