name: SubstituteUser
version: "0.1"
api-version: "1.13"
description: "Do something as somebody else"
author: Teddy
website: https://twieteddy.github.io
main: io.github.twieteddy.substituteuser.SubstituteUser
database: false

commands:
  su:
    description: Execute something as somebody else
    Usage: /su <onlinePlayer> <command>